version: '3.8'

services:
  build:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
   
    volumes:
    - ./dist:/usr/share/nginx/html
    networks:
      - frontend

networks:
  frontend:
    external: true
